### ISSUE TITLE
Issues with jumps (+ suggestion)

### ISSUE THREAD

**Issue by AnErrupTion** [toptensoftware/Sharp86#1]
Hello!

First of all, I want to thank you for that amazing piece of software. It's not an easy task to create even an Intel 8086 emulator!

Now, I'm currently having 2 issues related to jmps, and one suggestion.

So, I wanted to emulate just the FreeDOS boot floppy image, which should, in theory, work on an 8086. But I'm encountering a problem with ``0xEA`` (far jump) and ``0xEB`` (near jump).

For the near jump, it's supposed to jump at ``0x3E``, or in the emulator, ``ip + 0x3E``. That's because the near jump is **relative** to (I think) the value of IP. However, in that case, it should be the original value of IP (so where the program started).

The problem is that, in the code, it just sets the ``ip`` variable to the immediate value (``0x3E``), and as a result, the program would only continue executing if ``ip`` is originally 0 (and so the program is loaded at address 0).

And for the far jump, I'm not really sure. I've tried with the default value of IP and with 0, but it doesn't solve the problem. The instruction is as follows: ``jmp 0x1fe0:0x7c5e``. However, for whatever reason, it jumps somewhere where there is no code (every next opcode after this jump is 0). This is an absolute jump, so it's not the problem like above.

And finally, for the suggestion, it would be nice to have a "memory handler", similar to the interrupt handler. Basically, you'd be able to override a function, and detect the latest changes in memory. (For example in ``0xB8000``, although that'ts in protected mode, it'd still be handy for other things).

**Comment by toptensoftware** [comment]
I've had a quick look at this and both instructions are functioning as they should.

The far jump instruction (0xEA) just loads the CS:IP register pair from the 4 bytes that follow and continues execution from there.

The short jump instruction (0xEB) reads a byte from the next instruction, sign extends it and adds it the the IP after having read the jump instruction - ie: it's relative to the instruction after the jump, not the jump instruction itself.

As for providing a memory handlers, you can do that by providing your own implementation of Sharp86.IMemoryBus.

I hope this helps.

Brad

**Comment by AnErrupTion** [comment]
The problem that I have is that it seems to jump where there is no code. So my question now is: am I loading the program into memory correctly? Here's how I'm doing it:

``Buffer.BlockCopy(program, 0, _memory, (cs << 4) + ip, program.Length);``

This accounts for, as you can see, the original value of CS and IP. Is this incorrect? If so, it would be nice to add an example in the README to show how to properly load it.

**Comment by toptensoftware** [comment]
I can't really comment on this... it's really up to you to setup the correct execution environment, memory map, etc...  if there's no code at the location it's jumping to then that means you haven't loaded any code there - why that is I couldn't say.
